frida/frida-java-bridge

- index.js
- Removed resolution to wrong symbol `artQuickGenericJniTrampoline` (not a quick code, just inner impl.)
- Allow ArtMethod instance mutation via kFastNative flag (needed by method restoration when calling the original method)
- Sepearation between allocation ($alloc, corresponds to new-instance or Unsafe.allocateInstance) and initialization ($init, coressponds to &lt;init&gt;) - allows overriding of constructors
- Selective patching and restoration of individual ArtMethod fields
- Corrected a bug causing stack frame recognition of re-implemented methods to fail due to incorrect resolution of quick_generic_jni_trampoline
Suggestions are welcome!
> Cleanup & a few bug fixes regarding method re-implementation

- Makefile
- test/Makefile
if calling `make` from a makefile, use `$(MAKE)` which allows `-j` option to work properly
`adb push` doesn work like `cp` where you can `cp src1 src2 src3 dst`.  you have to push each file individually in `build/armeabi-v7a/runner build/tests.dex build/frida-java.js`
> makefile fixes

- lib/class-factory.js
- test/re/frida/MethodTest.java
Allow interception when a field and a method have the same name.
note : I've added some unit tests that I wasn't able to run (no build env here)
Should fix #20 :)
> handle field / method name collision

- lib/class-factory.js
- lib/env.js
This means we no longer use one global reference per class, and M + N
additional references for a class with M method and N fields.
The only long-lived global references we keep now are for instances, but
those are unavoidable. (And may be .dispose()d manually when desired.)
> Refactor to reduce global handle usage

- lib/class-factory.js
If a function prototype expects an array, currently, it may be hard to debug this as an exception is thrown relatively deep in the call stack.
To demonstrate this, I set a frida-java playground as detailed [here](https://gist.github.com/oleavr/cae76c895eb7d227216ed3ffe9dbbeb3), with the following invalid sample code:
```js
Java.perform(function () {
var X509TrustManager = Java.use('javax.net.ssl.X509TrustManager');
var SSLContext = Java.use('javax.net.ssl.SSLContext');
var SSLContext_init = SSLContext.init.overload('[Ljavax.net.ssl.KeyManager;',
'[Ljavax.net.ssl.TrustManager;', 'java.security.SecureRandom')
var TrustManager = Java.registerClass({
name: 'com.example.test.TrustManager',
implements: [X509TrustManager],
methods: {
checkClientTrusted: function (chain, authType) {
}, …
```
> Ensure that an Array was received in toJniObjectArray()

- lib/android.js
fixes #45
Added support for API 26 (Android 8). Not a 100% sure if this will function correctly when Android 9 arrives, since the method 'art::IndirectReferenceTable::Add' is now declared as optional, but this does work for API 25 & API 26.
> Update android.js - fixes #45

- lib/class-factory.js
- lib/env.js
- test/re/frida/MethodTest.java
Hi Ole André Vadla Ravnås,
I was trying to use this dereflection script from https://codeshare.frida.re/@dzonerzy/dereflector/
Unfortunately it was not working (Abort !).
I noticed that the prototype from `java.lang.Class.getMethod` set in the script was not the expected one (second parameter shall be `[java.lang.Class;` instead of `[java.lang.Object;`) but when I tried to set the correct type, frida said that it could not find the overload.
I tried to correct the problem in `frida-java` by calling `getParameterTypes` instead of `getGenericParameterTypes` and it seems to work.
Please find enclosed the modified dereflector script : [dereflector.js.gz](https://github.com/frida/frida-java/files/2167320/dereflector.js.gz)
As I am not very familiar with the internals of frida, I would like to …
> Allow hooking of java.lang.Class.getMethod

- lib/android.js
Fix "Unable to determine ClassLinker field offsets" on Android 8.0
> Changed ClassLinker discovery to properly track it on Android 8.0

- index.js
- lib/android.js
This PR is rolling back the apiLevel comparison that aligns correctly the classLinkerOffset on Android 8.0 and 8.1.
This is fixing the problem with the cache dir when hooking system_server as well.
> Fixing problems related to android runtime and hook on system_server

- lib/class-factory.js
it should also fix: #87, which happens when `GetStringUTFChars` is invoked.
[Reference](https://docs.oracle.com/javase/7/docs/technotes/guides/jni/spec/functions.html#string_operations)
> Fix return value handling for strings

- lib/android.js
sizeof(std::vector<int>) returned 24 on my 64-bit build, and 12 on 32-bit. So ti's the same as STD_STRING_SIZE, 3 pointers, begin, end, capacity.
> Adding missing STD_VECTOR_SIZE definition.

- lib/class-factory.js
- lib/mkdex.js
- test/re/frida/ClassCreationTest.java
I made an improvement for registerClass() to enable add user defined fields, such like below:
```
var UserDefinedFields = Java.registerClass({
name: 're.frida.SimpleFormatter',
implements: [Formatter],
fields: {
fieldInt: 'int',
fieldStr: 'java.lang.String',
},
methods: {
format: [{
returnType: 'java.lang.String',
argumentTypes: ['int'],
implementation: function (val) {
const self = Java.cast(this, UserDefinedFields);
const oldVal = self.fieldInt.value;
self.fieldInt.value = val;
return oldVal + ': ' + val;
}
}, {
returnType: 'java.lang.String',
argumentTypes: ['java.lang.String'],
implementation: function (val) {
const self = Java.cast(this, UserDefinedFields);
const oldVal = self.fieldStr.value;
self.fieldStr.value = val;
return oldVal + ': ' + val;
}
}]
}
});
```
> Enable add fields to registerClass() of Issue #76

- lib/class-factory.js
- lib/env.js
- test/re/frida/ClassRegistryTest.java
- test/re/frida/MethodTest.java
Fix for Issue #139, Java Wrapper's getClass() should return Wrapper of 'java.lang.Class'.
Fix for Issue #143, Java's fields should be accessible even without an instance.
> Fix for Issue #139 and Issue #143

- lib/env.js
[related issue](https://github.com/frida/frida/issues/1003)
parameters names change suggestion ? [source](https://docs.oracle.com/javase/8/docs/technotes/guides/jni/spec/functions.html) 
- env: the JNI interface pointer.
- array: a Java array.
- start: the starting index.
- len: the number of elements to be copied.
- buf: the destination buffer.
> add getByteArrayRegion

- lib/android.js
This pull request fixes two issues related to the support of Android R (or AOSP's master builds). My setup to reproduce those issues is the following:
- x86 Cuttlefish emulator (https://source.android.com/setup/create/cuttlefish)
- System images of build # 6355543 of AOSP's master branch (https://ci.android.com/builds/branches/aosp-master/grid) for Cuttlefish emulator (aosp_cf_x86_phone)
- Testing script
> Java.perform(() => {
console.log('Enumerating loaded classes...');
const classes = Java.enumerateLoadedClassesSync();
console.log(`Enumerated ${classes.length} classes`);
});
----------
The first issue is caused by missing APIs as shown in the following error
> Error: Java API only partially available; please file a bug. Missing: _ZN3art3Dbg9StartJdwpEv, _ZN3art3Dbg8GoActiveEv, …
> Fix missing APIs & ClassLinker offset calculation for Android R

- lib/env.js
- test/re/frida/MethodTest.java
as mentioned in https://github.com/frida/frida/issues/1308
in java utf-8 string 0x00 is encoded as 0xC080 instead of just 0x00, which will cause error in readUtf8String.  
see https://docs.oracle.com/javase/6/docs/api/java/io/DataInput.html#modified-utf-8
> add test for java modified utf-8

- index.js
- lib/android.js
- lib/api.js
- lib/class-factory.js
- lib/env.js
- lib/jvm.js
Hey!
I was doing some research and needed a Java instrumentation tool but Frida didn't work with JVMs yet.
Everything was pretty straight forward except for the method mangler which needed some custom code because JVMTI doesn't support the redefinition of java methods as native methods.
Enumerate classes and choose objects should work on all types of Java VMs which have JVMTI support but method interception has only been tested on HotSpot JVM on macOS (jdk >=8). Other platforms should work if the jvm library has symbols and Frida is able to find the correct APIs.
Thanks!
> Support for Java VM

- lib/jvm.js
Install new methods using VMThread::execute which blocks all Java
threads and makes it safer to do interception of hot methods.
However, compiled methods that are on the stack will still not be
flushed when calling the deoptimization logic. This is a problem
when reverting back to the old method and flushing the new method
which has been allocated using Frida’s Memory module. In this instance
we force the flushing of old compiled methods using the
NMethodSweeper::force_sweep API. We have to do it twice because of
some logic in nmethod::can_convert_to_zombie.
> Make method interception safer with VMThread

- lib/android.js
Android R introduced opaque JNI ids for methods and fields. See the commit: https://android.googlesource.com/platform/art/+/21d5994583c679cd5d8573b5d35dbd659bdca2c7.
The indirection mode will affect method hooks when enabled for the ART runtime since the 'methodId' returned from JNI function calls will be
set to a manged id instead of the "real" one that points to the 'ArtMethod'.
This mode will typically be enabled if the application has the 'debuggable' attribute set to true. See also https://android.googlesource.com/platform/art/+/refs/heads/master/runtime/runtime.cc#1075
> Properly support Android R

- lib/android.js
Fix Android 11 error:
```sh
frida-ps -aiU
Failed to enumerate applications: unable to determine Runtime.jni_ids_indirection_ offset
```
> Fix ART internals probing on Android 11/arm64

- lib/android.js
Since Android 11, Google removed the internal JDWP implementation from ART due to the risk of bit-rot ([reference](https://android.googlesource.com/platform/art/+/fc58809f7b932d86234130be15487017dc37b0cf)). This change causes the crashes discussed in PR #159 , and breaks the deoptimizeEverything function.
After investigating the related changes carefully, I think the only solution I can suggest is "drop the JDWP deoptimization solution for Android 11 and above, and rollback to the old hacky solution based on ART internal `Instrumentation` implementations." So, yep, ¯\_(ツ)_/¯
I've tested these codes on a Pixel 3a device with latest Android 11 release, but feel free to do more tests cause there may be some other edge cases I've never know before.
> Repair deoptimizeEverything() function for Android 11

- lib/android.js
Hi @oleavr , I've briefly checked the issue #186 , and figured out a more robust way to parse the offset for x86/x86_64 platforms. This could be helpful for future Android releases, and allow us to use `Instrumentation` on old devices in case of need.
BTW, I also added the throw back for API level >= 30, cause I thought this may be helpful for our debugging.
> Improve the logic about detecting instrumentation offset.

- index.js
- lib/android.js
Adds the method `Java.deoptimizeBootImage` which is similar to deoptimizeEverything but only ensures the deoptimization of code in the boot image oat files. This method works by simply calling `art::Runtime::DeoptimizeBootImage` which uses a class visitor to set the quickCode pointer to the interpreter bridge for every class in the boot image. This is a serious performance gain in some situations where the app code itself is slow when deoptimized and it is not necessary to do in order for hooks to be hit reliably.
> add Java.deoptimizeBootImage which calls art::Runtime::DeoptimizeBootImage

- Makefile
- lib/android.js
- test/Makefile
- test/re/frida/MethodTest.java
- test/runner.c
- Fix hooking of Interpreter internals on Android 5.0 & 5.1.
- Improve the test suite to include running with optimizations enabled (in-lining optimizations disabled).
- Fail explicitly when hooking an ArtMethod if it's too short and the prologue can't be overwritten, instead of hanging.
> Few fixes for ART

- lib/android.js
Since the replacement method that gets allocated by us is not visible to the ART runtime, it therefore
cannot be candidate for garbage collector visits when sweeps occur. In that case, the declaring_class_
field of ArtMethod (a GC root) could become stale after it gets moved to another memory space - resulting
in a crash when it is used after the fact.
Fixes https://github.com/frida/frida/issues/1609.
> Fix hooking of ART interpreter internals.

- lib/class-model.js
This is a bug where static initializer methods are being included in the enumerated set as '$init' while they should be skipped altogether.
> Fix result of Java.enumerateMethods on ART

- lib/types.js
- test/re/frida/MethodTest.java
This allows array objects obtained from the runtime to be reused later when marshaling array types, which is necessary in order to preserve type information in cases where the type is dynamic.
> Fix handling of generic array types

- index.js
- lib/android.js
add Java.deoptimizeMethod to call art::Dbg::RequestDeoptimization with selectiveDeoptimizaion option to deoptimize specific method.
This PR can provide frida to deoptimize specific method for the situation that specific method hooking is not taken effect. This will reduce the overhead for turn on all the deoptimizations and keep the app's running performance.
> add Java.deoptimizeMethod to call art::Dbg::RequestDeoptimization

- lib/android.js
Remove kAccSingleImplementation flag to avoid method being devirtualized so that frida can hook the method correctly
> Remove kAccSingleImplementation flag to avoid method being devirtualized

- lib/types.js
If the type of the array was not used in the application it means that it wasn't loaded in memory and Java.array failed because of this. This fix tries first to use the array type and if it fail, it will first create an empty array of that type using java.lang.reflect.Array.newInstance before calling factory.use.
> Fix Java.array for unloaded array types

- lib/env.js
A number of `JNIEnv` functions are currently exposed via the object returned by `Java.vm.getEnv()`, however `GetDirectBufferAddress` is missing.
This function is used when you need to share a raw byte buffer between managed and unmanaged code. In Frida, having it allows you to do heavy processing on Java's ByteBuffers via CModules when JS is just not fast enough, e.g. when hooking very hot media processing functions.
See https://docs.oracle.com/javase/7/docs/technotes/guides/jni/spec/functions.html#GetDirectBufferAddress
and https://developer.android.com/reference/java/nio/ByteBuffer#direct-vs.-non-direct-buffers for more information on direct byte buffers.
> Expose JNIEnv->GetDirectBufferAddress to JS

- lib/class-model.js
As shown by [#1644](https://github.com/frida/frida/issues/1644) the error message `Error: Invalid method query` is not really helpful as it does not give any hint how to change the method query parameter to make frida-trace accept it. 
I noticed that the pattern format is described in the [Java.enumerateMethods](https://frida.re/docs/javascript-api/#java) documentation so in my opinion we should change the error message to contain the basic pattern plus a hint where to find more details.
> frida-trace: improve error message for Java method searching

- lib/android.js
Some devices are getting "Unable to determine ClassLinker field offsets".
https://github.com/frida/frida/issues/2176
This could be related to ROM, or apparently "Google Play System Update".
Changing `classLinkerOffset = offset - (3 * pointerSize);` to `classLinkerOffset = offset - (4 * pointerSize);` fixed this issue for these devices, however so far it's unclear what is causing this change.
This workaround tries with `3` first, and if it fails, it tries `4`. I had to disable memoize because for some reason it wouldn't run with new arguments. The code isn't perfect, but it works, of course improvements by the community are most welcome.
Tested the same `frida-server` on multiple devices with and without the issue, and it seems to be resolved with this patch.
If allowed, I'd like to …
> [Fix] workaround for ClassLinker offset on Android 11 & 12

- lib/class-model.js
- test/re/frida/MethodTest.java
If "$" is used as a method name get function of wrapper does not handle it correctly.  This fixes the issue. I also added test for this. Not sure it is necessary
For the record malware packers use "$" as string decryption function name to avoid being hooked by frida :)
> Fix "$" method name is not handled correctly

- lib/class-factory.js
This is only a proposal of how to do it. Using only `Symbol` would be a bit verbose, so maybe only exposing it as a fallback would be okay?
I also used the global registry for symbols, we can also use a unique global `Symbol` variable if you think it would be better.
> Use symbols for unique property names 

- lib/android.js
This will fix https://github.com/frida/frida/issues/2468
> Make _ZNK3art6Thread13DecodeJObjectEP8_jobject optional

- lib/class-factory.js
- lib/env.js
With this PR you can instantiate java classes that do not have a constructor, by using the `java/lang/Object->init()` method.
I'm not sure if we need to handle more edge cases like the `isInterface` check.
> Add support for instantiating classes that do not have a constructor

- .github/workflows/tests.yml
- lib/types.js
- test/config.mk
- test/re/frida/MethodTest.java
Add test for #313 and implement a fix.
> Support arrays of array

- lib/class-factory.js
As of Android 14, apps with targetSdk >= 34 are not allowed to have writable permissions on dynamically loaded Dex files.
https://developer.android.com/about/versions/14/behavior-changes-14#safer-dynamic-code-loading
Attempting to call `Java.registerClass()` with such apps results in an exception being thrown:
```
java.lang.SecurityException: Writable dex file '/data/data/my.ebin.app/frida4706282976511766825.dex' is not allowed.
```
This removes writable permissions from the temporary DexFile created by `Java.registerClass()` after writing to it and before it gets loaded.
> fix(android): set DexFile to read-only in Java.registerClass()

- lib/mkdex.js
- test/re/frida/ClassCreationTest.java
registerClass creates wrong dex file when there are more than 2 fields #296 
This commit fixes two errors:
- field_ids items are not sorted. 
- field_idx_diff wrongly calculated. (0,1,2,3) needs to be (0,1,1,1)
Since we create 1 dex file for each registerClass, we don't need to keep track of field_idx_diff. (okay to begin from 0)
> fix: sort field items according to dex_file_verifier.cc

- lib/android.js
Fixes https://github.com/frida/frida-java-bridge/issues/323
It is related to this commit https://github.com/liuyufei/frida-java-bridge/commit/c52014e5ae1d864115a541265942bb330257c30b which was made to force an update of the ArtMethods containing the hooks after a GC. 
With the recent updates of Android/libart/Google Play System Updates on certain devices it has been enabled the CMC (MarkCompact collector) instead of CC (ConcurrentCopying).
> handle CMC GC strategy

- lib/android.js
Fixes https://github.com/frida/frida-java-bridge/issues/323.
The fix in https://github.com/frida/frida-java-bridge/pull/325 had 2 problems:
- with the Google Play System Updates the base version of libart can differ from the Android version( i.e. Android 12 device with libart 34)
- the function we were hooking in the MarkCompact GC was not stable enough causing crashes after some time. [tombstone_01.txt](https://github.com/user-attachments/files/16249961/tombstone_01.txt)
The proposed solution to the first point is to check if an exported symbol introduced in libart 34 is present.
The solution for the second problem is to hook the onEnter of art::Thread::RunFlipFunction
- this function is called also during in the ConcurrentCopying GC and in my tests didn't cause troubles but to avoid …
> android: Handle correctly the CMC GC strategy

- lib/android.js
In Android 15, `DecodeGlobal` is not available as `_ZN3art9JavaVMExt12DecodeGlobalEPv` is no longer exported by the ART runtime. Additionally, the fallback option `DecodeJObject` is ineffective because it's signature changed from `_ZNK3art6Thread13DecodeJObjectEP8_jobject` to `_ZNK3art6Thread19DecodeGlobalJObjectEP8_jobject` in some version between 6 and 14, throwing an unexpected error during `perform()` or `performNow()` calls.
This PR resolves the issue by making the Java API compatible with Android 15 and ensuring `DecodeJObject` is available if the fallback is needed.
Fixes #317
> android: Fix art::Thread::DecodeJObject for Android>=15

- lib/jvm.js
This change will make the `jvm.js` code be able to bridge Java OpenJDK 17 on Windows. This was tested on Windows 10, using `jdk-17.0.11+9` from https://learn.microsoft.com/en-gb/java/openjdk/download and the separately downloaded and extracted debug symbols.
The code is not pretty, but I've tried to keep as close to the original as possible.
Note the bug that I discovered while performing the tests; https://github.com/frida/frida-gum/issues/811. This means that the target process needs to be restarted after detaching Frida, for the Java bridge (resolving of Symbols) to work.
This code currently does not work with OpenJDK21!
This code requires the 'manual' placement of the debug symbols, otherwise `jvm.ts` will be unable to find the functions it requires.
> Feature: Will bridge Windows Java (OpenJDK17)

- lib/android.js
fix `Error: libart.so: unable to find export '_ZNK3art2gc4Heap15MayUseCollectorENS0_13CollectorTypeE`
eg: https://github.com/frida/frida/issues/2925
original change: https://github.com/frida/frida-java-bridge/pull/326
> android: fix bug where MayUseCollector is not available on some custom rom

- lib/class-factory.js
- lib/mkdex.js
With this PR, `registerClass` supports static methods. This also fixes the bug of not being able to implement static interface methods or static superClass methods.
`mkdex` now has the ability to add additional access flags like `ACC_STATIC` to non-constructor methods https://source.android.com/docs/core/runtime/dex-format#access-flags
To make a static method, add `isStatic: true` in the method object:
```js
Java.scheduleOnMainThread(() => 
{
Java.registerClass({
name: 'com.example.MyWeirdTrustManager',
superClass: SomeBaseClass,
implements: [X509TrustManager],
fields: {},
methods: {
checkServerTrusted: [{
isStatic: true,
returnType: 'void',
argumentTypes: ['[Ljava.security.cert.X509Certificate;', 'java.lang.String'],
implementation(chain, authType) {
console.log('checkServerTrusted A'); …
```
> registerClass static method support

- index.js
After executing `Java.enumerateLoadedClassesSync()` on certain devices and within multiple apps I got this error:
> signal 6 (SIGABRT) error, with code -6 (SI_TKILL) and fault address --------. 
The abort message reads: "JNI ERROR (app bug): global reference table overflow (max=51200). 
Global reference table dump: Last 10 entries (of 51200):".
This solution tested in several devices and work perfect.
> Fix JNI ERROR

- lib/android.js
Recent versions of ART can run on older Android versions. Because some of the ClassLinker’s specifications and method-invocation logic are tied exclusively to the API level, this pull request also considers the ART level to ensure compatibility
> android: Support new ART on compatible Android versions

- lib/android.js
bne.w instruction is now handled in arm recompile routine resulting in successful art thread state transition for cases where this instruction appears in the code being recompiled.
> fix handling conditional branch when recompiling for arm32

- lib/jvm.js
Patch to fix the issue with replacing JDK17 methods. See https://github.com/frida/frida-java-bridge/issues/333 for the full details.
> Fixing issue #333 with JDK17 method replacement

- lib/android.js
reverted unnecessary error throwing from PR [#343](https://github.com/frida/frida-java-bridge/pull/343) that caused inoperability on some Android 12 devices.
Related issues: https://github.com/frida/frida-java-bridge/issues/347
> revert unnecessary error throwing

- lib/class-factory.js
While migrating to using symbols, I migrated alloc with a wrong name.
Fixes #353
> Fix wrapper alloc

- lib/android.js
Addresses crashes commented under the previous pull request https://github.com/frida/frida-java-bridge/pull/359.
These fields shouldn't be optimised away.
Edit: Also added an extra check for the art array length. Sometimes it would read a negative number when trying offsets, and it would infinitely loop.
> Use stable fields for ART class spec offset detection

- lib/android.js
Hopefully my last PR regarding this. Thanks to @ExternalAddress4401 for providing repro code https://github.com/frida/frida-java-bridge/pull/361#issuecomment-3104746127.
This instance field should not be optimised out, see android code comment https://android.googlesource.com/platform/libcore.git/+/android-4.2.2_r1/luni/src/main/java/java/lang/Thread.java#133.
> some of these are accessed directly by the VM; do not rename them
> Use more stable fields for ART class spec offset detection
