test/Makefile

* we require a writable dalvik-cache directory
* create that directory and pass it in as an env variable

Support android 4

---

index.js
lib/class-factory.js
lib/env.js
lib/mkdex.js
lib/vm.js
package.json
test/re/frida/ClassCreationTest.java
test/re/frida/Eatable.java
test/re/frida/TestRunner.java
test/runner.c

This is useful for implementing an interface, e.g. `X509TrustManager`,
in just a few lines of JavaScript.

Add support for dynamic class creation

---

README.md
test/Makefile

Get frida's latest release version from github api.

improve the README

---

test/re/frida/MethodTest.java

Add test method to check returning of `CharacterSequence` types (#92 ).

add test case for returning strings

---

lib/android.js

This will fix the handling of LDR instructions in the arm64 thread state recompilation logic

Improve arm64 LDR-handling in thread state recompilation logic

---

lib/class-factory.js
lib/env.js
test/re/frida/ClassCreationTest.java
test/re/frida/MethodTest.java

Fixed for #119 Java.registerClass failed for interface with constants

Fixed for Issue #119/#121/#122/#123/#125

---

lib/mkdex.js
test/re/frida/ClassCreationTest.java

Enable user defined constructors in Java.registerClass().

Fixed for Issue #134, enable user defined constructors in Java.registerClass

---

lib/class-factory.js

Fix for Issue #141, Simultaneously invoke Java.use() will cause return wrong value.

Fix for Issue #141

---

lib/jvm.js

Fixes interception issues for static/final methods

Add JVM method adjustment logic

---

lib/android.js

Fix JDWP initialization failure on Android 7.1-8.1

---

lib/android.js

Fixes https://github.com/frida/frida/issues/1589.

Fix jni_ids_indirection_ offset parsing in ARM64

---

lib/android.js

Fix #207 by replacing the pointer for `num_frames` with an unsigned
integer and updating the function reference in `libart.so`

Add ARM32 / x86 / x64 support to StackVisitor 

---

lib/android.js

https://android-review.googlesource.com/c/platform/art/+/1634382
https://android-review.googlesource.com/c/platform/art/+/1636381
Tested on emulator arm64

add support for android 12 beta

---

test/Makefile
test/runner.c

There wasn't much to do, just to update to new function signatures

Update tests to new major version 16

---

.github/workflows/tests.yml

I should probably organize it a bit better, with test matrix and such but it works :)

Add GitHub Actions

---

lib/class-factory.js

Add toString method for overloads

---

lib/class-factory.js
lib/types.js

In general there is too much [object object]

class-factory: Add toString method to types and field

---

lib/class-factory.js
test/re/frida/MethodTest.java

class-factory: Fix toString for overloaded methods

---

lib/class-factory.js

Remove trailing comma to match style guide

---

lib/android.js

Make _ZNK3art6Thread13DecodeJObjectEP8_jobject optional

---

lib/android.js
lib/class-model.js

https://android-review.googlesource.com/c/platform/art/+/3380108

Support changes to art Class layout in android 16

---

lib/android.js

android: Fix typo: API level 34 != Android 16
